# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - pamsolik-cars

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Publish to Azure'     
        required: true
        default: 'warning'
      tags:
        description: 'Azure'

jobs:
  build:
    runs-on: windows-latest
    defaults:
            run:
              working-directory: ./Cars
    steps:
      - uses: actions/checkout@v2
      
      #- name: Remove artifacts
      #  uses: c-hive/gha-remove-artifacts@v1.2.0
      #  with:
          # Artifacts older than this will be deleted (e.g. "2 months", "1 day"). Parsed by moment.
      #     age: "1 day"
          # Access token for the repository, available under the same name in secrets.
      #    GITHUB_TOKEN: ${{ github.token }}
          # true/false. If enabled, tag build artifacts (e.g. release artifacts) will be kept.
      #     skip-tags: false
          # Keep the specified number of artifacts even if they are older than the age.
      #    skip-recent: 1
           
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Restore packages
        run: dotnet restore --locked-mode
        
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pamsolik-cars'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C70F76F364314562ADBFB9833ACBE06C }}
          package: .
