 - name: Remove artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        # Artifacts older than this will be deleted (e.g. "2 months", "1 day"). Parsed by moment.
        age: "1 day"
        # Access token for the repository, available under the same name in secrets.
        GITHUB_TOKEN: ${{ github.token }}
        # true/false. If enabled, tag build artifacts (e.g. release artifacts) will be kept.
        skip-tags: false
        # Keep the specified number of artifacts even if they are older than the age.
        skip-recent: 1
